<?php

/**
 * BaseLtRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $LtSurvey
 * 
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getLtSurvey() Returns the current record's "LtSurvey" collection
 * @method LtRegion            setName()     Sets the current record's "name" value
 * @method LtRegion            setLtSurvey() Sets the current record's "LtSurvey" collection
 * 
 * @package    LexLists
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLtRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('regions');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('LtSurvey', array(
             'local' => 'id',
             'foreign' => 'survey_region_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}