<?php

/**
 * BaseLtSurveyState
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $survey_id
 * @property integer $state_id
 * @property LtSurvey $Survey
 * @property LtState $State
 * 
 * @method integer       getSurveyId()  Returns the current record's "survey_id" value
 * @method integer       getStateId()   Returns the current record's "state_id" value
 * @method LtSurvey      getSurvey()    Returns the current record's "Survey" value
 * @method LtState       getState()     Returns the current record's "State" value
 * @method LtSurveyState setSurveyId()  Sets the current record's "survey_id" value
 * @method LtSurveyState setStateId()   Sets the current record's "state_id" value
 * @method LtSurveyState setSurvey()    Sets the current record's "Survey" value
 * @method LtSurveyState setState()     Sets the current record's "State" value
 * 
 * @package    LexLists
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLtSurveyState extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('survey_states');
        $this->hasColumn('survey_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('state_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LtSurvey as Survey', array(
             'local' => 'survey_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LtState as State', array(
             'local' => 'state_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}