<?php

/**
 * BaseLtCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $SurveyCities
 * @property Doctrine_Collection $LtSurveyCity
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getSurveyCities() Returns the current record's "SurveyCities" collection
 * @method Doctrine_Collection getLtSurveyCity() Returns the current record's "LtSurveyCity" collection
 * @method LtCity              setName()         Sets the current record's "name" value
 * @method LtCity              setSurveyCities() Sets the current record's "SurveyCities" collection
 * @method LtCity              setLtSurveyCity() Sets the current record's "LtSurveyCity" collection
 * 
 * @package    LexLists
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLtCity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cities');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('LtSurvey as SurveyCities', array(
             'refClass' => 'LtSurveyCity',
             'local' => 'city_id',
             'foreign' => 'survey_id'));

        $this->hasMany('LtSurveyCity', array(
             'local' => 'id',
             'foreign' => 'city_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}