<?php

/**
 * BaseLtSurveyCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $survey_id
 * @property integer $city_id
 * @property LtSurvey $Survey
 * @property LtCity $City
 * 
 * @method integer      getSurveyId()  Returns the current record's "survey_id" value
 * @method integer      getCityId()    Returns the current record's "city_id" value
 * @method LtSurvey     getSurvey()    Returns the current record's "Survey" value
 * @method LtCity       getCity()      Returns the current record's "City" value
 * @method LtSurveyCity setSurveyId()  Sets the current record's "survey_id" value
 * @method LtSurveyCity setCityId()    Sets the current record's "city_id" value
 * @method LtSurveyCity setSurvey()    Sets the current record's "Survey" value
 * @method LtSurveyCity setCity()      Sets the current record's "City" value
 * 
 * @package    LexLists
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLtSurveyCity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('survey_cities');
        $this->hasColumn('survey_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('city_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LtSurvey as Survey', array(
             'local' => 'survey_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LtCity as City', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}