<?php

/**
 * BaseLtSurveyContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $email_address
 * @property string $phone_number
 * @property Doctrine_Collection $LtSurvey
 * 
 * @method string              getFirstName()     Returns the current record's "first_name" value
 * @method string              getLastName()      Returns the current record's "last_name" value
 * @method string              getEmailAddress()  Returns the current record's "email_address" value
 * @method string              getPhoneNumber()   Returns the current record's "phone_number" value
 * @method Doctrine_Collection getLtSurvey()      Returns the current record's "LtSurvey" collection
 * @method LtSurveyContact     setFirstName()     Sets the current record's "first_name" value
 * @method LtSurveyContact     setLastName()      Sets the current record's "last_name" value
 * @method LtSurveyContact     setEmailAddress()  Sets the current record's "email_address" value
 * @method LtSurveyContact     setPhoneNumber()   Sets the current record's "phone_number" value
 * @method LtSurveyContact     setLtSurvey()      Sets the current record's "LtSurvey" collection
 * 
 * @package    LexLists
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLtSurveyContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('survey_contacts');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone_number', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('LtSurvey', array(
             'local' => 'id',
             'foreign' => 'survey_contact_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}