<?php

/**
 * BaseLtSurveySpecialCriteria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $survey_id
 * @property integer $special_criteria_id
 * @property LtSurvey $Survey
 * @property LtSpecialCriteria $SpecialCriteria
 * 
 * @method integer                 getSurveyId()            Returns the current record's "survey_id" value
 * @method integer                 getSpecialCriteriaId()   Returns the current record's "special_criteria_id" value
 * @method LtSurvey                getSurvey()              Returns the current record's "Survey" value
 * @method LtSpecialCriteria       getSpecialCriteria()     Returns the current record's "SpecialCriteria" value
 * @method LtSurveySpecialCriteria setSurveyId()            Sets the current record's "survey_id" value
 * @method LtSurveySpecialCriteria setSpecialCriteriaId()   Sets the current record's "special_criteria_id" value
 * @method LtSurveySpecialCriteria setSurvey()              Sets the current record's "Survey" value
 * @method LtSurveySpecialCriteria setSpecialCriteria()     Sets the current record's "SpecialCriteria" value
 * 
 * @package    LexLists
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLtSurveySpecialCriteria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('survey_special_criterias');
        $this->hasColumn('survey_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('special_criteria_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LtSurvey as Survey', array(
             'local' => 'survey_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LtSpecialCriteria as SpecialCriteria', array(
             'local' => 'special_criteria_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}