<?php

/**
 * BaseLtSurveyPracticeArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $survey_id
 * @property integer $practice_area_id
 * @property LtSurvey $Survey
 * @property LtPracticeArea $PracticeArea
 * 
 * @method integer              getSurveyId()         Returns the current record's "survey_id" value
 * @method integer              getPracticeAreaId()   Returns the current record's "practice_area_id" value
 * @method LtSurvey             getSurvey()           Returns the current record's "Survey" value
 * @method LtPracticeArea       getPracticeArea()     Returns the current record's "PracticeArea" value
 * @method LtSurveyPracticeArea setSurveyId()         Sets the current record's "survey_id" value
 * @method LtSurveyPracticeArea setPracticeAreaId()   Sets the current record's "practice_area_id" value
 * @method LtSurveyPracticeArea setSurvey()           Sets the current record's "Survey" value
 * @method LtSurveyPracticeArea setPracticeArea()     Sets the current record's "PracticeArea" value
 * 
 * @package    LexLists
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLtSurveyPracticeArea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('survey_practice_areas');
        $this->hasColumn('survey_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('practice_area_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LtSurvey as Survey', array(
             'local' => 'survey_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LtPracticeArea as PracticeArea', array(
             'local' => 'practice_area_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}