<?php

/**
 * BaseLtClient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property boolean $is_enabled
 * @property Doctrine_Collection $sfGuardUser
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method boolean             getIsEnabled()   Returns the current record's "is_enabled" value
 * @method Doctrine_Collection getSfGuardUser() Returns the current record's "sfGuardUser" collection
 * @method LtClient            setName()        Sets the current record's "name" value
 * @method LtClient            setIsEnabled()   Sets the current record's "is_enabled" value
 * @method LtClient            setSfGuardUser() Sets the current record's "sfGuardUser" collection
 * 
 * @package    LexLists
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLtClient extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clients');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_enabled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser', array(
             'local' => 'id',
             'foreign' => 'client_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}