<?php

/**
 * BaseLtPracticeArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $main_practice_area_id
 * @property string $name
 * @property string $short_code
 * @property LtMainPracticeArea $MainPracticeArea
 * @property Doctrine_Collection $SurveyPracticeAreas
 * @property Doctrine_Collection $LtSurveyPracticeArea
 * 
 * @method integer             getMainPracticeAreaId()    Returns the current record's "main_practice_area_id" value
 * @method string              getName()                  Returns the current record's "name" value
 * @method string              getShortCode()             Returns the current record's "short_code" value
 * @method LtMainPracticeArea  getMainPracticeArea()      Returns the current record's "MainPracticeArea" value
 * @method Doctrine_Collection getSurveyPracticeAreas()   Returns the current record's "SurveyPracticeAreas" collection
 * @method Doctrine_Collection getLtSurveyPracticeArea()  Returns the current record's "LtSurveyPracticeArea" collection
 * @method LtPracticeArea      setMainPracticeAreaId()    Sets the current record's "main_practice_area_id" value
 * @method LtPracticeArea      setName()                  Sets the current record's "name" value
 * @method LtPracticeArea      setShortCode()             Sets the current record's "short_code" value
 * @method LtPracticeArea      setMainPracticeArea()      Sets the current record's "MainPracticeArea" value
 * @method LtPracticeArea      setSurveyPracticeAreas()   Sets the current record's "SurveyPracticeAreas" collection
 * @method LtPracticeArea      setLtSurveyPracticeArea()  Sets the current record's "LtSurveyPracticeArea" collection
 * 
 * @package    LexLists
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLtPracticeArea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('practice_areas');
        $this->hasColumn('main_practice_area_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('name', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('short_code', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LtMainPracticeArea as MainPracticeArea', array(
             'local' => 'main_practice_area_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('LtSurvey as SurveyPracticeAreas', array(
             'refClass' => 'LtSurveyPracticeArea',
             'local' => 'practice_area_id',
             'foreign' => 'survey_id'));

        $this->hasMany('LtSurveyPracticeArea', array(
             'local' => 'id',
             'foreign' => 'practice_area_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}