<?php

/**
 * LtCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LtCityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LtCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LtCity');
    }
}