<?php

/**
 * LtClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LtClientTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object LtClientTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('LtClient');
  }

  /**
   * Checking client name for uniqueness
   * 
   * @param string   $client_name       Email address
   * @param integer  $client_id         ID of user
   * 
   * @return object LtClientTable
   */
  public function checkUniqueClientName($client_name, $client_id = false) {
    $q = $this->createQuery('c')
            ->where('c.name = ?', $client_name);

    if ($client_id !== false) {
      $q->andWhere('c.id <> ?', $client_id);
    }

    $result = $q->fetchOne();

    return $result;
  }

}
