<?php

/**
 * LtCountryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LtCountryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LtCountryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LtCountry');
    }
}