<?php

/**
 * LtMySurvey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    LexLists
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LtMySurvey extends BaseLtMySurvey {

    /**
     *  My statuses
     */
    const MY_STATUS_DEFINITE = 1;
    const MY_STATUS_MAYBE    = 2;
    
    /**
     *  My statuses array
     */
    static public $my_statuses_array = array(
        self::MY_STATUS_DEFINITE => "Definite",
        self::MY_STATUS_MAYBE    => "Maybe"
    );

}
