<?php

/**
 * LtOrganizationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LtOrganizationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LtOrganizationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LtOrganization');
    }
}