<?php

/**
 * LtPracticeAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LtPracticeAreaTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object LtPracticeAreaTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('LtPracticeArea');
    }
    
    /**
     * Get all practice areas
     * 
     * @return object LtPracticeAreaTable
     */
    public function getAllPracticeAreas() {
        $q = $this->createQuery("pa")
                ->orderBy("pa.short_code ASC");
        
        return $q->execute();
    }

}
