<?php

/**
 * LtRegionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LtRegionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LtRegionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LtRegion');
    }
}