<?php

/**
 * LtStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LtStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LtStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LtState');
    }
}