<?php

/**
 * LtSurveySpecialCriteriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LtSurveySpecialCriteriaTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object LtSurveySpecialCriteriaTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('LtSurveySpecialCriteria');
  }
  
  /**
   * Delete all rows related to particular survey
   * 
   * @param integer $survey_id    ID of survey
   * 
   * @return object LtSurveyStateTable
   */
  public function deleteOldRows($survey_id) {
    $q = $this->createQuery("ssc")
            ->delete()
            ->where("ssc.survey_id = ?", $survey_id);
    
    return $q->execute();
  }

}
