<?php

/**
 * LtSurveyContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LtSurveyContactTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object LtSurveyContactTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('LtSurveyContact');
  }
  
  /**
   * Get syrvey contacts
   * 
   * @return array
   */
    public function getSurveyContacts() {
        $q = $this->createQuery('u');

        $result = $q->orderBy('u.first_name');

        $survey_contacts = $result->execute();

        $survey_contacts_array = array();
        if ($survey_contacts->getFirst()) {
            foreach ($survey_contacts as $survey_contact) {
                $email_address = "";
                if ($survey_contact->getEmailAddress() != '') {
                    $email_address = " (Email: ";
                    $email_address .= $survey_contact->getEmailAddress();
                }

                $phone = "";
                if ($survey_contact->getPhoneNumber() != '') {
                    if($email_address == "")
                    {
                        $phone =  "(Phone: " ;
                    }
                    else{
                        $phone =  ", Phone: " ;
                    }

                    $phone .= $survey_contact->getPhoneNumber();
                }

                $scope = "";
                if($email_address != "" || $phone != "")
                {
                    $scope = ")";
                }

                $survey_contact_last_name = "";
                if($survey_contact->getLastName() != '')
                {
                    $survey_contact_last_name = $survey_contact->getLastName().", ";
                }

                $survey_contact_first_name = "";
                if($survey_contact->getFirstName() != '')
                {
                    $survey_contact_first_name = $survey_contact->getFirstName()." ";
                }

                $survey_contacts_array[$survey_contact->getId()] = $survey_contact_last_name . $survey_contact_first_name . $email_address . $phone . $scope;
            }
        }

        return $survey_contacts_array;
    }

    /**
     * Get syrvey emails
     *
     * @return array
     */
    public function getSurveyEmails() {
        $q = $this->createQuery('u');

        $result = $q->orderBy('u.first_name');

        $survey_contacts = $result->execute();
        $arrEmails = array();
        if ($survey_contacts->getFirst()) {
            foreach ($survey_contacts as $survey_contact) {
                if ($survey_contact->getEmailAddress() != '') {
                    $email_address = $survey_contact->getEmailAddress();
                    $arrEmails[] = $email_address;
                }

            }
        }

        return $arrEmails;
    }

}
