generator:
  class: sfDoctrineGenerator
  param:
    model_class:           LtClient
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          lt_client
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        name: { attributes: { class: required } }
      list:    
        title: List Of Clients
        display: [name,is_enabled, created_at]
        max_per_page: 20
      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     ~
