generator:
  class: sfDoctrineGenerator
  param:
    model_class:           LtSurvey
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          lt_survey
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        organization_id:        { attributes: { with_add_new_link: true } }
        cities_list:            { attributes: { with_add_new_link: true } }
        survey_contact_id:      { attributes: { with_add_new_link: true } }
      list:    
        title: List Of Surveys
        max_per_page: 20
        display: [organization, year, survey_name, submission_deadline, updated_at]
        fields:
          submission_deadline:  {label: Submission Deadline, date_format: dd-MMM-y}
          updated_at:  {label: Last Update, date_format: dd-MMM-y HH:mm}
      filter:
        class: LtSurveyFormFilter
      form:    
        class: SurveyManagementForm
      edit:    ~
      new:     ~
